### ISSUE TITLE
HTTPError: 500 Server Error

### ISSUE THREAD

**Issue by Christophe-Freyre** [pelkmanslab/TissueMAPS-OLD#23]
While trying to upload locally original images (tiff) to TissueMAPS I get the following error message:
Jo has the same problem using a different dataset.
![http error 500](https://cloud.githubusercontent.com/assets/11965283/22646288/e84a1f68-ec6b-11e6-8c5d-019ac2b3659c.png)

**Comment by jluethi** [comment]
Also uploading via the user interface shows the same error in the console (though it still puts the files on "complete" in the viewer.

![screen shot 2017-02-06 at 12 55 57](https://cloud.githubusercontent.com/assets/18033446/22646355/3aafa2fa-ec6c-11e6-9b43-3d3f66cc0a2d.png)

**Comment by scottberry** [comment]
I also have the same error when uploading onto an instance of tissuemaps-v0.2.0[dev-20170214]. The upload is from an instance made with the tm_client image. I have not tried to upload on the browser.

Here is the error report.

```
2017-02-16 11:31:59 | DEBUG    | tmclient.base                            | login in as: "testuser"
2017-02-16 11:31:59 | DEBUG    | tmclient.base                            | url: http://172.23.92.111:80/auth
2017-02-16 11:32:00 | DEBUG    | tmclient.api                             | get ID for experiment "CytooStarter2"
2017-02-16 11:32:00 | DEBUG    | tmclient.base                            | url: http://172.23.92.111:80/api/experiments?name=CytooStarter2
2017-02-16 11:32:00 | DEBUG    | tmclient.api                             | call method "upload_microscope_files"
2017-02-16 11:32:00 | INFO     | tmclient.api                             | upload microscope files of plate "test3Dvisi" and acquisition "test3Dvisi"
2017-02-16 11:32:00 | DEBUG    | tmclient.api                             | get acquisition ID given acquisition "test3Dvisi" and plate "test3Dvisi"
2017-02-16 11:32:00 | DEBUG    | tmclient.base                            | url: http://172.23.92.111:80/api/experiments/dG1hcHMy/acquisitions?plate_name=test3Dvisi&name=test3Dvisi
2017-02-16 11:32:00 | INFO     | tmclient.api                             | register files for upload of acquisition dG1hcHMx
2017-02-16 11:32:00 | DEBUG    | tmclient.base                            | url: http://172.23.92.111:80/api/experiments/dG1hcHMy/acquisitions/dG1hcHMx/upload/register
2017-02-16 11:32:00 | INFO     | tmclient.api                             | upload file: starter2_1_w2sdcCy5_s601.stk
2017-02-16 11:32:00 | DEBUG    | tmclient.api                             | upload file "/home/ubuntu/data/Data/Users/Scott/Cytoo/20170106_CytooStarter2/starter2_1_w2sdcCy5_s601.stk" for acquisition dG1hcHMx
2017-02-16 11:32:00 | DEBUG    | tmclient.base                            | url: http://172.23.92.111:80/api/experiments/dG1hcHMy/acquisitions/dG1hcHMx/upload/upload-file
Traceback (most recent call last):
  File "/usr/local/bin/tm_client", line 9, in <module>
    load_entry_point('tmclient==0.0.1', 'console_scripts', 'tm_client')()
  File "build/bdist.linux-x86_64/egg/tmclient/api.py", line 108, in __main__
  File "build/bdist.linux-x86_64/egg/tmclient/api.py", line 91, in __call__
  File "build/bdist.linux-x86_64/egg/tmclient/api.py", line 725, in upload_microscope_files
  File "build/bdist.linux-x86_64/egg/tmclient/api.py", line 775, in _upload_file
  File "/usr/local/lib/python2.7/dist-packages/requests-2.12.4-py2.7.egg/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://172.23.92.111:80/api/experiments/dG1hcHMy/acquisitions/dG1hcHMx/upload/upload-file
```

**Comment by jluethi** [comment]
That's interesting. When I try to upload something on the 0.2.0 version with the tm_client, it directly fails with the following error for me. In the user interface, it now works again for me though...

tm_client -vv -H 130.60.24.212 -u testuser -p XXXXXX -e Joel_ClassifierTest upload -d /Volumes/data/Data/Users/Joel/20161101_BleedthroughOptimization/TIFF/ microscope_file -p p1 -a a1
2017-02-15 18:33:01 | INFO     | tmclient.api                             | upload microscope files of plate "p1" and acquisition "a1"
Traceback (most recent call last):
  File "/usr/local/bin/tm_client", line 11, in <module>
    sys.exit(TmClient.__main__())
  File "/usr/local/lib/python2.7/site-packages/tmclient/api.py", line 108, in __main__
    client(args)
  File "/usr/local/lib/python2.7/site-packages/tmclient/api.py", line 91, in __call__
    method(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/tmclient/api.py", line 718, in upload_microscope_files
    acquisition_id = self._get_acquisition_id(plate_name, acquisition_name)
  File "/usr/local/lib/python2.7/site-packages/tmclient/api.py", line 490, in _get_acquisition_id
    return data[0]['id']
IndexError: list index out of range

**Comment by hackermd** [comment]
These are two unrelated issues. @jluethi please create a separate issue. Did you create an an acquisition before uploading files? It seems the server didn't find an acquisition. The error handling could be improved.

**Comment by hackermd** [comment]
@scottberry Can you get the corresponding uwsgi log ? This would help to figure out what's going on server side.

**Comment by scottberry** [comment]
For me, this error seems to be because the volume is full. I didn't realise my dataset was so big

here are the last few lines of the uwsgi.log. I deleted the experiment now and am trying to attach a bigger volume.

```
2017-02-16 12:12:21 | INFO     | tmserver.api.experiment                  | get plates for experiment 2
[pid: 1197|app: 0|req: 553/9081] 130.60.76.122 () {42 vars in 919 bytes} [Thu Feb 16 12:12:21 2017] GET /api/experiments/dG1hcHMy/plates => generated 310 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 12:12:31 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 2
[pid: 1199|app: 0|req: 564/9082] 130.60.76.122 () {42 vars in 937 bytes} [Thu Feb 16 12:12:31 2017] GET /api/experiments/dG1hcHMy/workflow/status => generated 19 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
2017-02-16 12:12:31 | INFO     | tmserver.api.experiment                  | get plates for experiment 2
[pid: 1195|app: 0|req: 369/9083] 130.60.76.122 () {42 vars in 919 bytes} [Thu Feb 16 12:12:31 2017] GET /api/experiments/dG1hcHMy/plates => generated 310 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 12:12:41 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 2
[pid: 1200|app: 0|req: 682/9084] 130.60.76.122 () {42 vars in 937 bytes} [Thu Feb 16 12:12:41 2017] GET /api/experiments/dG1hcHMy/workflow/status => generated 19 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
2017-02-16 12:12:41 | INFO     | tmserver.api.experiment                  | get plates for experiment 2
[pid: 1202|app: 0|req: 360/9085] 130.60.76.122 () {42 vars in 919 bytes} [Thu Feb 16 12:12:41 2017] GET /api/experiments/dG1hcHMy/plates => generated 310 bytes in 15 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 12:12:51 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 2
[pid: 1193|app: 0|req: 514/9086] 130.60.76.122 () {42 vars in 937 bytes} [Thu Feb 16 12:12:51 2017] GET /api/experiments/dG1hcHMy/workflow/status => generated 19 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
2017-02-16 12:12:51 | INFO     | tmserver.api.experiment                  | get plates for experiment 2
[pid: 1193|app: 0|req: 515/9087] 130.60.76.122 () {42 vars in 919 bytes} [Thu Feb 16 12:12:51 2017] GET /api/experiments/dG1hcHMy/plates => generated 310 bytes in 14 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 12:13:01 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 2
[pid: 1204|app: 0|req: 317/9088] 130.60.76.122 () {42 vars in 937 bytes} [Thu Feb 16 12:13:01 2017] GET /api/experiments/dG1hcHMy/workflow/status => generated 19 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
2017-02-16 12:13:01 | INFO     | tmserver.api.experiment                  | get plates for experiment 2
[pid: 1198|app: 0|req: 1545/9089] 130.60.76.122 () {42 vars in 919 bytes} [Thu Feb 16 12:13:01 2017] GET /api/experiments/dG1hcHMy/plates => generated 310 bytes in 17 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 12:13:11 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 2
[pid: 1200|app: 0|req: 683/9090] 130.60.76.122 () {42 vars in 937 bytes} [Thu Feb 16 12:13:11 2017] GET /api/experiments/dG1hcHMy/workflow/status => generated 19 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
2017-02-16 12:13:11 | INFO     | tmserver.api.experiment                  | get plates for experiment 2
[pid: 1199|app: 0|req: 565/9091] 130.60.76.122 () {42 vars in 919 bytes} [Thu Feb 16 12:13:11 2017] GET /api/experiments/dG1hcHMy/plates => generated 310 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 12:13:15 | INFO     | tmserver.api.experiment                  | get experiments
[pid: 1197|app: 0|req: 554/9092] 130.60.76.122 () {42 vars in 887 bytes} [Thu Feb 16 12:13:15 2017] GET /api/experiments => generated 290 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 12:14:40 | INFO     | tmserver.api.experiment                  | delete experiment 2
2017-02-16 12:14:40 | INFO     | tmlib.models.utils                       | drop schema of experiment 2
[pid: 1195|app: 0|req: 370/9093] 130.60.76.122 () {44 vars in 943 bytes} [Thu Feb 16 12:14:40 2017] DELETE /api/experiments/dG1hcHMy => generated 22 bytes in 6664 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
```

**Comment by scottberry** [comment]
But I guess this part of uwsgi.log first part is more interesting.

```
2017-02-16 11:23:11 | INFO     | tmserver.api.experiment                  | get experiments
2017-02-16 11:23:11 | INFO     | tmserver.api.experiment                  | filter experiments for name "20170111-184A1-NascentRNACycler-Stack"
[pid: 1200|app: 0|req: 631/8381] 172.23.82.3 () {38 vars in 749 bytes} [Thu Feb 16 11:23:11 2017] GET /api/experiments?name=20170111-184A1-NascentRNACycler-Stack => generated 164 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 11:23:11 | INFO     | tmserver.api.experiment                  | get acquistions for experiment 2
[pid: 1200|app: 0|req: 632/8382] 172.23.82.3 () {38 vars in 767 bytes} [Thu Feb 16 11:23:11 2017] GET /api/experiments/dG1hcHMy/acquisitions?plate_name=test3D&name=test3D => generated 136 bytes in 12 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 11:23:12 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 2
[pid: 1198|app: 0|req: 1481/8383] 130.60.76.122 () {42 vars in 937 bytes} [Thu Feb 16 11:23:12 2017] GET /api/experiments/dG1hcHMy/workflow/status => generated 19 bytes in 8 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
2017-02-16 11:23:12 | INFO     | tmserver.api.experiment                  | get plates for experiment 2
[pid: 1199|app: 0|req: 518/8384] 130.60.76.122 () {42 vars in 919 bytes} [Thu Feb 16 11:23:12 2017] GET /api/experiments/dG1hcHMy/plates => generated 310 bytes in 15 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 11:23:22 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 2
[pid: 1195|app: 0|req: 326/8385] 130.60.76.122 () {42 vars in 937 bytes} [Thu Feb 16 11:23:22 2017] GET /api/experiments/dG1hcHMy/workflow/status => generated 19 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
2017-02-16 11:23:22 | INFO     | tmserver.api.experiment                  | get plates for experiment 2
[pid: 1190|app: 0|req: 434/8386] 130.60.76.122 () {42 vars in 919 bytes} [Thu Feb 16 11:23:22 2017] GET /api/experiments/dG1hcHMy/plates => generated 310 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
[pid: 1203|app: 0|req: 866/8387] 172.23.82.3 () {42 vars in 847 bytes} [Thu Feb 16 11:23:11 2017] POST /api/experiments/dG1hcHMy/acquisitions/dG1hcHMx/upload/register => generated 354508 bytes in 16250 msecs (HTTP/1.1 200) 2 headers in 75 bytes (5 switches on core 99)
2017-02-16 11:23:27 | ERROR    | wsgi                                     | Exception on /api/experiments/dG1hcHMy/acquisitions/dG1hcHMx/upload/upload-file [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 161[pid: 1203|app: 0|req: 867/8388] 172.23.82.3 () {42 vars in 949 bytes} [Thu Feb 16 11:23:27 2017] POST /api/experiments/dG1hcHMy/acquisitions/dG1hcHMx/upload/upload-file => generated 291 bytes in 34 msecs (HTTP/1.1 500) 2 headers in 84 bytes (59 switches on core 99)
2017-02-16 11:23:32 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 2
[pid: 1193|app: 0|req: 469/8389] 130.60.76.122 () {42 vars in 937 bytes} [Thu Feb 16 11:23:32 2017] GET /api/experiments/dG1hcHMy/workflow/status => generated 19 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
2017-02-16 11:23:32 | INFO     | tmserver.api.experiment                  | get plates for experiment 2
[pid: 1189|app: 0|req: 384/8390] 130.60.76.122 () {42 vars in 919 bytes} [Thu Feb 16 11:23:32 2017] GET /api/experiments/dG1hcHMy/plates => generated 310 bytes in 19 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
[pid: 1196|app: 0|req: 662/8391] 172.23.82.3 () {40 vars in 510 bytes} [Thu Feb 16 11:23:38 2017] POST /auth => generated 212 bytes in 325 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 11:23:38 | INFO     | tmserver.api.experiment                  | get experiments
2017-02-16 11:23:38 | INFO     | tmserver.api.experiment                  | filter experiments for name "20170111-184A1-NascentRNACycler-Stack"
[pid: 1195|app: 0|req: 327/8392] 172.23.82.3 () {38 vars in 749 bytes} [Thu Feb 16 11:23:38 2017] GET /api/experiments?name=20170111-184A1-NascentRNACycler-Stack => generated 164 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 11:23:38 | INFO     | tmserver.api.experiment                  | get acquistions for experiment 2
[pid: 1197|app: 0|req: 506/8393] 172.23.82.3 () {38 vars in 767 bytes} [Thu Feb 16 11:23:38 2017] GET /api/experiments/dG1hcHMy/acquisitions?plate_name=test3D&name=test3D => generated 136 bytes in 14 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 11:23:42 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 2
[pid: 1200|app: 0|req: 633/8394] 130.60.76.122 () {42 vars in 937 bytes} [Thu Feb 16 11:23:42 2017] GET /api/experiments/dG1hcHMy/workflow/status => generated 19 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
2017-02-16 11:23:42 | INFO     | tmserver.api.experiment                  | get plates for experiment 2
[pid: 1199|app: 0|req: 519/8395] 130.60.76.122 () {42 vars in 919 bytes} [Thu Feb 16 11:23:42 2017] GET /api/experiments/dG1hcHMy/plates => generated 310 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 11:23:52 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 2
[pid: 1189|app: 0|req: 385/8396] 130.60.76.122 () {42 vars in 937 bytes} [Thu Feb 16 11:23:52 2017] GET /api/experiments/dG1hcHMy/workflow/status => generated 19 bytes in 8 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
2017-02-16 11:23:52 | INFO     | tmserver.api.experiment                  | get plates for experiment 2
[pid: 1191|app: 0|req: 321/8397] 130.60.76.122 () {42 vars in 919 bytes} [Thu Feb 16 11:23:52 2017] GET /api/experiments/dG1hcHMy/plates => generated 310 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
[pid: 1198|app: 0|req: 1482/8398] 172.23.82.3 () {42 vars in 847 bytes} [Thu Feb 16 11:23:38 2017] POST /api/experiments/dG1hcHMy/acquisitions/dG1hcHMx/upload/register => generated 354508 bytes in 15731 msecs (HTTP/1.1 200) 2 headers in 75 bytes (6 switches on core 99)
2017-02-16 11:23:54 | ERROR    | wsgi                                     | Exception on /api/experiments/dG1hcHMy/acquisitions/dG1hcHMx/upload/upload-file [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 16[pid: 1198|app: 0|req: 1483/8399] 172.23.82.3 () {42 vars in 949 bytes} [Thu Feb 16 11:23:54 2017] POST /api/experiments/dG1hcHMy/acquisitions/dG1hcHMx/upload/upload-file => generated 291 bytes in 33 msecs (HTTP/1.1 500) 2 headers in 84 bytes (57 switches on core 99)
2017-02-16 11:24:01 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 2
[pid: 1199|app: 0|req: 520/8400] 130.60.76.122 () {42 vars in 937 bytes} [Thu Feb 16 11:24:01 2017] GET /api/experiments/dG1hcHMy/workflow/status => generated 19 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
2017-02-16 11:24:01 | INFO     | tmserver.api.experiment                  | get plates for experiment 2
[pid: 1203|app: 0|req: 868/8401] 130.60.76.122 () {42 vars in 919 bytes} [Thu Feb 16 11:24:01 2017] GET /api/experiments/dG1hcHMy/plates => generated 310 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
[pid: 1196|app: 0|req: 663/8402] 172.23.82.3 () {40 vars in 510 bytes} [Thu Feb 16 11:24:04 2017] POST /auth => generated 212 bytes in 309 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 11:24:05 | INFO     | tmserver.api.experiment                  | get experiments
2017-02-16 11:24:05 | INFO     | tmserver.api.experiment                  | filter experiments for name "20170111-184A1-NascentRNACycler-Stack"
[pid: 1200|app: 0|req: 634/8403] 172.23.82.3 () {38 vars in 749 bytes} [Thu Feb 16 11:24:05 2017] GET /api/experiments?name=20170111-184A1-NascentRNACycler-Stack => generated 164 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 11:24:05 | INFO     | tmserver.api.experiment                  | get acquistions for experiment 2
[pid: 1192|app: 0|req: 456/8404] 172.23.82.3 () {38 vars in 767 bytes} [Thu Feb 16 11:24:05 2017] GET /api/experiments/dG1hcHMy/acquisitions?plate_name=test3D&name=test3D => generated 136 bytes in 13 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
2017-02-16 11:24:12 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 2
[pid: 1197|app: 0|req: 507/8405] 130.60.76.122 () {42 vars in 937 bytes} [Thu Feb 16 11:24:12 2017] GET /api/experiments/dG1hcHMy/workflow/status => generated 19 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
2017-02-16 11:24:12 | INFO     | tmserver.api.experiment                  | get plates for experiment 2
[pid: 1201|app: 0|req: 363/8406] 130.60.76.122 () {42 vars in 919 bytes} [Thu Feb 16 11:24:12 2017] GET /api/experiments/dG1hcHMy/plates => generated 310 bytes in 18 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
[pid: 1195|app: 0|req: 328/8407] 172.23.82.3 () {42 vars in 847 bytes} [Thu Feb 16 11:24:05 2017] POST /api/experiments/dG1hcHMy/acquisitions/dG1hcHMx/upload/register => generated 354508 bytes in 16284 msecs (HTTP/1.1 200) 2 headers in 75 bytes (5 switches on core 99)
2017-02-16 11:24:21 | ERROR    | wsgi                                     | Exception on /api/experiments/dG1hcHMy/acquisitions/dG1hcHMx/upload/upload-file [POST]
```

**Comment by hackermd** [comment]
Ok, the disk size problem is easy to fix :)

We may want to improve error handling and forward certain server error messages to the client. I've create an issue for that TissueMAPS/TmClient#7
