### ISSUE TITLE
TM 0.2.0: Problems in the viewer & can't submit SVM

### ISSUE THREAD

**Issue by jluethi** [pelkmanslab/TissueMAPS-OLD#26]
Running the new release on an image with some processed data lead to some problems in the viewer:
It was quite slow to load images (probably related to slower access to the parallel database?) and it had a constant stream of error messages in the console that I am not familiar with.

The main problem though is that when I try to submit an SVM (or a different classifier), nothing happens in the interface. In the console, it says "ToolService: START REQUEST", followed by a server error where the important part is probably this:
 "tools/request 500 (Internal Server Error)"

![image 63480f85-ec2d-4419-9a85-5a36131d4593 home](https://cloud.githubusercontent.com/assets/18033446/23063730/46d1ec34-f50c-11e6-919e-a4b141ed19a5.png)

But now, I can't even train new classifiers anymore, because when I reopened the viewer, all my processed objects are not shown anymore & not selectable. Also all the plate, well & site information is not loaded anymore.

![screen shot 2017-02-17 at 08 47 58](https://cloud.githubusercontent.com/assets/18033446/23063750/656f73dc-f50c-11e6-9c30-6b6c44c0e8a0.png)

**Comment by hackermd** [comment]
This was a bug introduced upon recent refactoring. Fixed with TissueMAPS/TmServer@3ec0d4d7b0087ac7bc2efec5733ca3b2f7e3c395

**Comment by alecrimi** [comment]
The error is generated from a version with already those changes

**Comment by jluethi** [comment]
This fix solved the problems with the error messages and I could then submit an SVM. I got the confirmation that the job was submitted, but for some reason, it never returned a result. Maybe a timeout?

I tried again today and now I'm getting the same errors as before again. 
@alecrimi Was anything changed concerning this fix between Friday evening and now? Is this fix still present in the most recent built that you pulled on the server?

![screen shot 2017-02-20 at 10 54 00](https://cloud.githubusercontent.com/assets/18033446/23120113/606a750c-f75b-11e6-8580-94058cc9d398.png)

**Comment by alecrimi** [comment]
yes, I updated it, but it was supposed for something else

**Comment by jluethi** [comment]
So is the fix from above still there in the current version? Can you check for that?

**Comment by alecrimi** [comment]
yes it is there.

**Comment by hackermd** [comment]
I would check the following:
- checked out git commit tag of repositories `tmlibrary` and `tmserver`
- status of the submitted tool task in the database
- log of the tool job in `/storage/experiments/experiment_<id>/tools/log`

You can also rerun the tool job on the server via the command line, see `tm_tool -h`.

**Comment by alecrimi** [comment]
There is something suspicious which needs attention from this morning at 10.53

> 2017-02-20 09:53:53 | INFO     | tmserver.api.tools                       | process request of tool "Classification"
2017-02-20 09:53:53 | ERROR    | wsgi                                     | Exception on /api/experiments/dG1hcHMz/tools/request [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask_jwt/__init__.py", line 177, in decorator
    return fn(*args, **kwargs)
  File "/home/ubuntu/tmserver/tmserver/util.py", line 207, in wrapped
    return f(*args, **kwargs)
  File "/home/ubuntu/tmserver/tmserver/util.py", line 104, in wrapped
    return f(*args, **kwargs)
  File "/home/ubuntu/tmserver/tmserver/api/tools.py", line 169, in process_tool_request
    manager.store_payload(payload, submission_id)
  File "/usr/local/lib/python2.7/dist-packages/tmlib/tools/manager.py", line 173, in store_payload
    if not isinstance(batch, dict):
NameError: global name 'batch' is not defined

**Comment by hackermd** [comment]
Fixed with TissueMAPS/TmLibrary@ffcc1457c069dc01f42ad41751953eefd8990d0b

**Comment by alecrimi** [comment]
Although there are some submissions from this morning at the same time of the error, there is no tasks running in any state right now.

select * from submissions ;
>  19 | tool     |             3 |       1 |             | 2017-02-20 09:53:37.113385 | 2017-02-20 09:53:37.113385
 20 | tool     |             3 |       1 |             | 2017-02-20 09:53:51.082599 | 2017-02-20 09:53:51.082599
 21 | tool     |             3 |       1 |             | 2017-02-20 09:53:52.867516 | 2017-02-20 09:53:52.867516
 22 | tool     |             3 |       1 |             | 2017-02-20 09:53:53.825234 | 2017-02-20 09:53:53.825234
 23 | tool     |             3 |       1 |             | 2017-02-20 09:53:57.800972 | 2017-02-20 09:53:57.800972
 24 | tool     |             3 |       1 |             | 2017-02-20 09:53:59.021734 | 2017-02-20 09:53:59.021734

select * from tasks;
> id  |   state    |           name           | exitcode |    time     | memory |  cpu_time   |          type           | is_collection |

**Comment by alecrimi** [comment]
With this new fix, the names of the features are gone.
And the inspector is giving also this error:
GET http://130.60.24.212/images/ui-bg_highlight-soft_100_eeeeee_1x100.png 404 (NOT FOUND)

**Comment by alecrimi** [comment]
The fix worked, there was a mess in the instance because there were 2 tmlib installed inside /usr/local/lib/python2.7/dist-packages . Now everything is fine. This are preliminary results using SVM and 10 random features
![screen shot 2017-02-20 at 17 53 06](https://cloud.githubusercontent.com/assets/16406658/23135160/c0d03c56-f797-11e6-9fa8-53c156b2349c.png)

**Comment by scottberry** [comment]
I also experienced the same error (no result returned to the UI), running
https://github.com/TissueMAPS/TmLibrary/commit/ee42fbafd6d16e5c6bd1a2febed651a417676043

(later than the fix specified above)

Here is the .out and .err file from the relevant tool

```
ubuntu@tissuemaps-scott-server-001:/storage/experiments/experiment_14/tools/logs$ cat tool_Classification_2017-02-27_08-14-23.out

            )           (
         ( /(           )\
         )\()) (    (  ((_)
        (_))/  )\   )\  _     TissueMAPS tool request manager (tmlib 0.2.0)
        | |_  ((_) ((_)| |    https://github.com/TissueMAPS/TmLibrary
        |  _|/ _ \/ _ \| |
         \__|\___/\___/|_|


2017-02-27 08:14:37 | INFO     | tmlib.tools.base                         | perform classification using "svm" method
```

```
ubuntu@tissuemaps-scott-server-001:/storage/experiments/experiment_14/tools/logs$ cat tool_Classification_2017-02-27_08-19-12.err
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/tm_tool", line 11, in <module>
    load_entry_point('tmlibrary', 'console_scripts', 'tm_tool')()
  File "/home/ubuntu/tmlibrary/tmlib/tools/manager.py", line 238, in __main__
    tool.process_request(args.submission_id, payload)
  File "/home/ubuntu/tmlibrary/tmlib/tools/classification.py", line 97, in process_request
    feature_data, labels, method, n_fold_cv
  File "/home/ubuntu/tmlibrary/tmlib/tools/base.py", line 391, in classify_supervised
    scaler.fit(feature_data)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sklearn/preprocessing/data.py", line 1006, in fit
    X = self._check_array(X, self.copy)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sklearn/preprocessing/data.py", line 983, in _check_array
    ensure_2d=False, estimator=self, dtype=FLOAT_DTYPES)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sklearn/utils/validation.py", line 407, in check_array
    _assert_all_finite(array)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sklearn/utils/validation.py", line 58, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```
