### ISSUE TITLE
Not all channels in 3D dataset update in viewer when using z-slider

### ISSUE THREAD

**Issue by scottberry** [pelkmanslab/TissueMAPS-OLD#32]
3D dataset processed (2 channel Yokogawa images) on test instance on science cloud http://172.23.93.94/. Experiment name: 20170111-184A1-NascentRNACycler-Stack

https://github.com/TissueMAPS/TmLibrary/commit/ee42fbafd6d16e5c6bd1a2febed651a417676043
https://github.com/TissueMAPS/TmServer/commit/1f8969319761f7c9f8a65495e08eb18c0081dd5c
https://github.com/TissueMAPS/TmUI/commit/123571786b9f04e77afacdaccd90c0a54ae561e1

When the z-slider is used, some of the sites are not updated in the viewer. This can sometimes be fixed by zooming in and out. 

@SaadiaIftikhar @HackerMD, I will leave this data on the test instance for you to have a look.

Example:
![screen shot 2017-02-22 at 09 08 17](https://cloud.githubusercontent.com/assets/5407848/23202507/847dcf00-f8de-11e6-9fde-12c4f0ba9ba0.png)

**Comment by hackermd** [comment]
This could be due to browser cache. Can you please try after emptying or disabling the cache.

**Comment by scottberry** [comment]
Still present with cache killer ON. It is not a particularly serious issue but log in and have a look.

**Comment by hackermd** [comment]
I could also see this on my machine with cache disabled. I then checked the number of tiles per layer and z-level in the database:

```SQL
SELECT channel_layer_id, z, count(id) FROM experiment_1.channel_layer_tiles
GROUP BY channel_layer_id, z
ORDER BY channel_layer_id, z;
```

All tiles were there.

Then I restarted the server and tiles loaded perfectly fine... Did you restart the server after updating the code?

**Comment by scottberry** [comment]
yes

**Comment by scottberry** [comment]
Also fixed for me now.

I guess that means a “refresh” step needs to be added somewhere when the “view” function is executed for 3D data.

**Comment by hackermd** [comment]
No, that shouldn't be required.

I don't know why this error occurred. I found the following message in the logs:

```
2017-02-22 09:34:17 | ERROR    | wsgi                                     | Exception on /api/experiments/dG1hcHMx/channel_layers/dG1hcHM5MQ==/tiles [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/tmserver/tmserver/util.py", line 68, in wrapped
    return f(*args, **kwargs)
  File "/home/ubuntu/tmserver/tmserver/util.py", line 207, in wrapped
    return f(*args, **kwargs)
  File "/home/ubuntu/tmserver/tmserver/api/layer.py", line 65, in get_channel_layer_tile
    x, y, z, channel_layer.zplane, channel_layer.tpoint
AttributeError: 'NoneType' object has no attribute 'zplane'
```

So apparently the server was not able to retrieve a `channel_layer` by its ID. This error didn't occur again after server restart.

**Comment by scottberry** [comment]
This is fixed.
