### ISSUE TITLE
Download issue: Big dataset runs into issues

### ISSUE THREAD

**Issue by jluethi** [pelkmanslab/TissueMAPS-OLD#70]
Trying to download a data set with hundreds of features currently fails mid-way and appends the error message at the end of the data. I can't figure out what is going wrong here.
We were using this command:
tm_client -vv -H app.tissuemaps.org -u rdegro -p XXX feature-values -e NUP_FollowUp1_20x_Try6 download -o Cells --directory ~/
Thus downloading data from experiment_90 currently fails.

This is the error message attached to the feature values:

```

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"

  <head>

    <title>InternalError: (psycopg2.InternalError) failed to execute job 26183

DETAIL:  Failure due to failed task 96

 [SQL: 'SELECT mapobjects.id AS mapobjects_id, mapobject_segmentations.label AS mapobject_segmentations_label, mapobject_segmentations.segmentation_layer_id AS mapobject_segmentations_segmentation_layer_id \nFROM mapobjects JOIN mapobject_segmentations ON mapobjects.id = mapobject_segmentations.mapobject_id \nWHERE mapobjects.mapobject_type_id = %(mapobject_type_id_1)s AND ST_Intersects(mapobject_segmentations.geom_centroid, ST_GeomFromEWKB(%(ST_GeomFromEWKB_1)s)) AND mapobject_segmentations.segmentation_layer_id IN (%(segmentation_layer_id_1)s, %(segmentation_layer_id_2)s, %(segmentation_layer_id_3)s, %(segmentation_layer_id_4)s, %(segmentation_layer_id_5)s) ORDER BY mapobjects.id'] [parameters: {'ST_GeomFromEWKB_1': &lt;read-only buffer for 0x7f263f2cdf30, size 93, offset 0 at 0x7f263a137730&gt;, 'segmentation_layer_id_3': 11, 'segmentation_layer_id_2': 10, 'mapobject_type_id_1': 10, 'segmentation_layer_id_1': 8, 'segmentation_layer_id_4': 6, 'segmentation_layer_id_5': 7}] // Werkzeug Debugger</title>

    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css"

    <!-- We need to make sure this has a favicon so that the debugger does

         not by accident trigger a request to /favicon.ico which might

         change the application state. -->

        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">

    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>

    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>

    <script type="text/javascript">

      var TRACEBACK = 139802161484560,

          CONSOLE_MODE = false,

          EVALEX_TRUSTED = false,

          SECRET = "vVArcnaXmrGfIJDIZB3T";

  </head>

    <div class="debugger">

<h1>sqlalchemy.exc.InternalError</h1>

<div class="detail">

  <p class="errormsg">InternalError: (psycopg2.InternalError) failed to execute job 26183

DETAIL:  Failure due to failed task 96

 [SQL: 'SELECT mapobjects.id AS mapobjects_id, mapobject_segmentations.label AS mapobject_segmentations_label, mapobject_segmentations.segmentation_layer_id AS mapobject_segmentations_segmentation_layer_id \nFROM mapobjects JOIN mapobject_segmentations ON mapobjects.id = mapobject_segmentations.mapobject_id \nWHERE mapobjects.mapobject_type_id = %(mapobject_type_id_1)s AND ST_Intersects(mapobject_segmentations.geom_centroid, ST_GeomFromEWKB(%(ST_GeomFromEWKB_1)s)) AND mapobject_segmentations.segmentation_layer_id IN (%(segmentation_layer_id_1)s, %(segmentation_layer_id_2)s, %(segmentation_layer_id_3)s, %(segmentation_layer_id_4)s, %(segmentation_layer_id_5)s) ORDER BY mapobjects.id'] [parameters: {'ST_GeomFromEWKB_1': &lt;read-only buffer for 0x7f263f2cdf30, size 93, offset 0 at 0x7f263a137730&gt;, 'segmentation_layer_id_3': 11, 'segmentation_layer_id_2': 10, 'mapobject_type_id_1': 10, 'segmentation_layer_id_1': 8, 'segmentation_layer_id_4': 6, 'segmentation_layer_id_5': 7}]</p>

<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>

<div class="traceback">

  <ul><li><div class="frame" id="frame-139802158423184">

  <h4>File <cite class="filename">"/home/tissuemaps/.local/lib/python2.7/site-packages/werkzeug/wsgi.py"</cite>,

      line <em class="line">703</em>,

      in <code class="function">__next__</code></h4>

  <div class="source"><pre class="line before"><span class="ws"></span> </pre>

<pre class="line before"><span class="ws">    </span>def __iter__(self):</pre>

<pre class="line before"><span class="ws">        </span>return self</pre>

<pre class="line before"><span class="ws"></span> </pre>

<pre class="line before"><span class="ws">    </span>def __next__(self):</pre>

<pre class="line current"><span class="ws">        </span>return self._next()</pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws">    </span>def close(self):</pre>

<pre class="line after"><span class="ws">        </span>for callback in self._callbacks:</pre>

<pre class="line after"><span class="ws">            </span>callback()</pre>

<pre class="line after"><span class="ws"></span> </pre></div>

<li><div class="frame" id="frame-139802160914000">

  <h4>File <cite class="filename">"/home/tissuemaps/.local/lib/python2.7/site-packages/werkzeug/wrappers.py"</cite>,

      line <em class="line">81</em>,

      in <code class="function">_iter_encoded</code></h4>

  <div class="source"><pre class="line before"><span class="ws">                           </span>'form data.  If you really want to do '</pre>

<pre class="line before"><span class="ws">                           </span>'that, set `shallow` to False.')</pre>

<pre class="line before"><span class="ws"></span> </pre>

<pre class="line before"><span class="ws"></span> </pre>

<pre class="line before"><span class="ws"></span>def _iter_encoded(iterable, charset):</pre>

<pre class="line current"><span class="ws">    </span>for item in iterable:</pre>

<pre class="line after"><span class="ws">        </span>if isinstance(item, text_type):</pre>

<pre class="line after"><span class="ws">            </span>yield item.encode(charset)</pre>

<pre class="line after"><span class="ws">        </span>else:</pre>

<pre class="line after"><span class="ws">            </span>yield item</pre>

<pre class="line after"><span class="ws"></span> </pre></div>

<li><div class="frame" id="frame-139802159508176">

  <h4>File <cite class="filename">"/home/tissuemaps/tmserver/tmserver/api/feature.py"</cite>,

      line <em class="line">314</em>,

      in <code class="function">generate_feature_matrix</code></h4>

  <div class="source"><pre class="line before"><span class="ws">                </span>filter_by(ref_type=tm.Site.__name__).\</pre>

<pre class="line before"><span class="ws">                </span>one()</pre>

<pre class="line before"><span class="ws">            </span>for site_id in site_ids:</pre>

<pre class="line before"><span class="ws">                </span>results = _get_mapobjects_at_site(</pre>

<pre class="line before"><span class="ws">                    </span>session, mapobject_type_id, site_mapobject_type.id,</pre>

<pre class="line current"><span class="ws">                    </span>site_id, layer_lut.keys()</pre>

<pre class="line after"><span class="ws">                </span>)</pre>

<pre class="line after"><span class="ws">                </span>for mapobject_id, label, segmenation_layer_id in results:</pre>

<pre class="line after"><span class="ws">                    </span># One could nicely filter features values using slice()</pre>

<pre class="line after"><span class="ws">                    </span>feature_values = session.query(tm.FeatureValues.values).\</pre>

<pre class="line after"><span class="ws">                        </span>filter_by(mapobject_id=mapobject_id).\</pre></div>

<li><div class="frame" id="frame-139802158603856">

  <h4>File <cite class="filename">"/home/tissuemaps/tmserver/tmserver/api/mapobject.py"</cite>,

      line <em class="line">132</em>,

      in <code class="function">_get_mapobjects_at_site</code></h4>

  <div class="source"><pre class="line before"><span class="ws">            </span>),</pre>

<pre class="line before"><span class="ws">            </span>tm.MapobjectSegmentation.segmentation_layer_id.in_(</pre>

<pre class="line before"><span class="ws">                </span>segmentation_layer_ids</pre>

<pre class="line before"><span class="ws">            </span>)</pre>

<pre class="line before"><span class="ws">        </span>).\</pre>

<pre class="line current"><span class="ws">        </span>order_by(tm.Mapobject.id).\</pre>

<pre class="line after"><span class="ws">        </span>all()</pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws"></span>def _get_border_mapobjects_at_site(session, mapobject_ids,</pre>

<pre class="line after"><span class="ws">        </span>site_mapobject_type_id, site_id):</pre></div>

<li><div class="frame" id="frame-139802158603792">

  <h4>File <cite class="filename">"/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py"</cite>,

      line <em class="line">2679</em>,

      in <code class="function">all</code></h4>

  <div class="source"><pre class="line before"><span class="ws">        </span>&quot;&quot;&quot;Return the results represented by this ``Query`` as a list.</pre>

<pre class="line before"><span class="ws"></span> </pre>

<pre class="line before"><span class="ws">        </span>This results in an execution of the underlying query.</pre>

<pre class="line before"><span class="ws"></span> </pre>

<pre class="line before"><span class="ws">        </span>&quot;&quot;&quot;</pre>

<pre class="line current"><span class="ws">        </span>return list(self)</pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws">    </span>@_generative(_no_clauseelement_condition)</pre>

<pre class="line after"><span class="ws">    </span>def from_statement(self, statement):</pre>

<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;Execute the given SELECT statement and return results.</pre>

<pre class="line after"><span class="ws"></span> </pre></div>

<li><div class="frame" id="frame-139802158603600">

  <h4>File <cite class="filename">"/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py"</cite>,

      line <em class="line">2831</em>,

      in <code class="function">__iter__</code></h4>

  <div class="source"><pre class="line before"><span class="ws">    </span>def __iter__(self):</pre>

<pre class="line before"><span class="ws">        </span>context = self._compile_context()</pre>

<pre class="line before"><span class="ws">        </span>context.statement.use_labels = True</pre>

<pre class="line before"><span class="ws">        </span>if self._autoflush and not self._populate_existing:</pre>

<pre class="line before"><span class="ws">            </span>self.session._autoflush()</pre>

<pre class="line current"><span class="ws">        </span>return self._execute_and_instances(context)</pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws">    </span>def __str__(self):</pre>

<pre class="line after"><span class="ws">        </span>context = self._compile_context()</pre>

<pre class="line after"><span class="ws">        </span>try:</pre>

<pre class="line after"><span class="ws">            </span>bind = self._get_bind_args(</pre></div>

<li><div class="frame" id="frame-139802158603088">

  <h4>File <cite class="filename">"/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py"</cite>,

      line <em class="line">2854</em>,

      in <code class="function">_execute_and_instances</code></h4>

  <div class="source"><pre class="line before"><span class="ws">        </span>conn = self._get_bind_args(</pre>

<pre class="line before"><span class="ws">            </span>querycontext,</pre>

<pre class="line before"><span class="ws">            </span>self._connection_from_session,</pre>

<pre class="line before"><span class="ws">            </span>close_with_result=True)</pre>

<pre class="line before"><span class="ws"></span> </pre>

<pre class="line current"><span class="ws">        </span>result = conn.execute(querycontext.statement, self._params)</pre>

<pre class="line after"><span class="ws">        </span>return loading.instances(querycontext.query, result, querycontext)</pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws">    </span>def _get_bind_args(self, querycontext, fn, **kw):</pre>

<pre class="line after"><span class="ws">        </span>return fn(</pre>

<pre class="line after"><span class="ws">            </span>mapper=self._bind_mapper(),</pre></div>

<li><div class="frame" id="frame-139802158604240">

  <h4>File <cite class="filename">"/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py"</cite>,

      line <em class="line">945</em>,

      in <code class="function">execute</code></h4>

  <div class="source"><pre class="line before"><span class="ws">        </span>try:</pre>

<pre class="line before"><span class="ws">            </span>meth = object._execute_on_connection</pre>

<pre class="line before"><span class="ws">        </span>except AttributeError:</pre>

<pre class="line before"><span class="ws">            </span>raise exc.ObjectNotExecutableError(object)</pre>

<pre class="line before"><span class="ws">        </span>else:</pre>

<pre class="line current"><span class="ws">            </span>return meth(self, multiparams, params)</pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws">    </span>def _execute_function(self, func, multiparams, params):</pre>

<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;Execute a sql.FunctionElement object.&quot;&quot;&quot;</pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws">        </span>return self._execute_clauseelement(func.select(),</pre></div>

<li><div class="frame" id="frame-139802158601488">

  <h4>File <cite class="filename">"/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py"</cite>,

      line <em class="line">263</em>,

      in <code class="function">_execute_on_connection</code></h4>

  <div class="source"><pre class="line before"><span class="ws">            </span># self</pre>

<pre class="line before"><span class="ws">            </span>return self</pre>

<pre class="line before"><span class="ws"></span> </pre>

<pre class="line before"><span class="ws">    </span>def _execute_on_connection(self, connection, multiparams, params):</pre>

<pre class="line before"><span class="ws">        </span>if self.supports_execution:</pre>

<pre class="line current"><span class="ws">            </span>return connection._execute_clauseelement(self, multiparams, params)</pre>

<pre class="line after"><span class="ws">        </span>else:</pre>

<pre class="line after"><span class="ws">            </span>raise exc.ObjectNotExecutableError(self)</pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws">    </span>def unique_params(self, *optionaldict, **kwargs):</pre>

<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;Return a copy with :func:`bindparam()` elements replaced.</pre></div>

<li><div class="frame" id="frame-139802158601744">

  <h4>File <cite class="filename">"/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py"</cite>,

      line <em class="line">1053</em>,

      in <code class="function">_execute_clauseelement</code></h4>

  <div class="source"><pre class="line before"><span class="ws">        </span>ret = self._execute_context(</pre>

<pre class="line before"><span class="ws">            </span>dialect,</pre>

<pre class="line before"><span class="ws">            </span>dialect.execution_ctx_cls._init_compiled,</pre>

<pre class="line before"><span class="ws">            </span>compiled_sql,</pre>

<pre class="line before"><span class="ws">            </span>distilled_params,</pre>

<pre class="line current"><span class="ws">            </span>compiled_sql, distilled_params</pre>

<pre class="line after"><span class="ws">        </span>)</pre>

<pre class="line after"><span class="ws">        </span>if self._has_events or self.engine._has_events:</pre>

<pre class="line after"><span class="ws">            </span>self.dispatch.after_execute(self,</pre>

<pre class="line after"><span class="ws">                                        </span>elem, multiparams, params, ret)</pre>

<pre class="line after"><span class="ws">        </span>return ret</pre></div>

<li><div class="frame" id="frame-139802158603280">

  <h4>File <cite class="filename">"/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py"</cite>,

      line <em class="line">1189</em>,

      in <code class="function">_execute_context</code></h4>

  <div class="source"><pre class="line before"><span class="ws">            </span>self._handle_dbapi_exception(</pre>

<pre class="line before"><span class="ws">                </span>e,</pre>

<pre class="line before"><span class="ws">                </span>statement,</pre>

<pre class="line before"><span class="ws">                </span>parameters,</pre>

<pre class="line before"><span class="ws">                </span>cursor,</pre>

<pre class="line current"><span class="ws">                </span>context)</pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws">        </span>if self._has_events or self.engine._has_events:</pre>

<pre class="line after"><span class="ws">            </span>self.dispatch.after_cursor_execute(self, cursor,</pre>

<pre class="line after"><span class="ws">                                               </span>statement,</pre>

<pre class="line after"><span class="ws">                                               </span>parameters,</pre></div>

<li><div class="frame" id="frame-139802158600592">

  <h4>File <cite class="filename">"/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py"</cite>,

      line <em class="line">1393</em>,

      in <code class="function">_handle_dbapi_exception</code></h4>

  <div class="source"><pre class="line before"><span class="ws">            </span>if newraise:</pre>

<pre class="line before"><span class="ws">                </span>util.raise_from_cause(newraise, exc_info)</pre>

<pre class="line before"><span class="ws">            </span>elif should_wrap:</pre>

<pre class="line before"><span class="ws">                </span>util.raise_from_cause(</pre>

<pre class="line before"><span class="ws">                    </span>sqlalchemy_exception,</pre>

<pre class="line current"><span class="ws">                    </span>exc_info</pre>

<pre class="line after"><span class="ws">                </span>)</pre>

<pre class="line after"><span class="ws">            </span>else:</pre>

<pre class="line after"><span class="ws">                </span>util.reraise(*exc_info)</pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws">        </span>finally:</pre></div>

<li><div class="frame" id="frame-139802158600976">

  <h4>File <cite class="filename">"/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/util/compat.py"</cite>,

      line <em class="line">203</em>,

      in <code class="function">raise_from_cause</code></h4>

  <div class="source"><pre class="line before"><span class="ws"></span>def raise_from_cause(exception, exc_info=None):</pre>

<pre class="line before"><span class="ws">    </span>if exc_info is None:</pre>

<pre class="line before"><span class="ws">        </span>exc_info = sys.exc_info()</pre>

<pre class="line before"><span class="ws">    </span>exc_type, exc_value, exc_tb = exc_info</pre>

<pre class="line before"><span class="ws">    </span>cause = exc_value if exc_value is not exception else None</pre>

<pre class="line current"><span class="ws">    </span>reraise(type(exception), exception, tb=exc_tb, cause=cause)</pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws"></span>if py3k:</pre>

<pre class="line after"><span class="ws">    </span>exec_ = getattr(builtins, 'exec')</pre>

<pre class="line after"><span class="ws"></span>else:</pre>

<pre class="line after"><span class="ws">    </span>def exec_(func_text, globals_, lcl=None):</pre></div>

<li><div class="frame" id="frame-139802158600848">

  <h4>File <cite class="filename">"/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py"</cite>,

      line <em class="line">1182</em>,

      in <code class="function">_execute_context</code></h4>

  <div class="source"><pre class="line before"><span class="ws">                </span>if not evt_handled:</pre>

<pre class="line before"><span class="ws">                    </span>self.dialect.do_execute(</pre>

<pre class="line before"><span class="ws">                        </span>cursor,</pre>

<pre class="line before"><span class="ws">                        </span>statement,</pre>

<pre class="line before"><span class="ws">                        </span>parameters,</pre>

<pre class="line current"><span class="ws">                        </span>context)</pre>

<pre class="line after"><span class="ws">        </span>except BaseException as e:</pre>

<pre class="line after"><span class="ws">            </span>self._handle_dbapi_exception(</pre>

<pre class="line after"><span class="ws">                </span>e,</pre>

<pre class="line after"><span class="ws">                </span>statement,</pre>

<pre class="line after"><span class="ws">                </span>parameters,</pre></div>

<li><div class="frame" id="frame-139802158603664">

  <h4>File <cite class="filename">"/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/default.py"</cite>,

      line <em class="line">470</em>,

      in <code class="function">do_execute</code></h4>

  <div class="source"><pre class="line before"><span class="ws"></span> </pre>

<pre class="line before"><span class="ws">    </span>def do_executemany(self, cursor, statement, parameters, context=None):</pre>

<pre class="line before"><span class="ws">        </span>cursor.executemany(statement, parameters)</pre>

<pre class="line before"><span class="ws"></span> </pre>

<pre class="line before"><span class="ws">    </span>def do_execute(self, cursor, statement, parameters, context=None):</pre>

<pre class="line current"><span class="ws">        </span>cursor.execute(statement, parameters)</pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws">    </span>def do_execute_no_params(self, cursor, statement, context=None):</pre>

<pre class="line after"><span class="ws">        </span>cursor.execute(statement)</pre>

<pre class="line after"><span class="ws"></span> </pre>

<pre class="line after"><span class="ws">    </span>def is_disconnect(self, e, connection, cursor):</pre></div>

  <blockquote>InternalError: (psycopg2.InternalError) failed to execute job 26183

DETAIL:  Failure due to failed task 96

 [SQL: 'SELECT mapobjects.id AS mapobjects_id, mapobject_segmentations.label AS mapobject_segmentations_label, mapobject_segmentations.segmentation_layer_id AS mapobject_segmentations_segmentation_layer_id \nFROM mapobjects JOIN mapobject_segmentations ON mapobjects.id = mapobject_segmentations.mapobject_id \nWHERE mapobjects.mapobject_type_id = %(mapobject_type_id_1)s AND ST_Intersects(mapobject_segmentations.geom_centroid, ST_GeomFromEWKB(%(ST_GeomFromEWKB_1)s)) AND mapobject_segmentations.segmentation_layer_id IN (%(segmentation_layer_id_1)s, %(segmentation_layer_id_2)s, %(segmentation_layer_id_3)s, %(segmentation_layer_id_4)s, %(segmentation_layer_id_5)s) ORDER BY mapobjects.id'] [parameters: {'ST_GeomFromEWKB_1': &lt;read-only buffer for 0x7f263f2cdf30, size 93, offset 0 at 0x7f263a137730&gt;, 'segmentation_layer_id_3': 11, 'segmentation_layer_id_2': 10, 'mapobject_type_id_1': 10, 'segmentation_layer_id_1': 8, 'segmentation_layer_id_4': 6, 'segmentation_layer_id_5': 7}]</blockquote>

<div class="plain">

  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">

      <input type="hidden" name="language" value="pytb">

      This is the Copy/Paste friendly version of the traceback.  <span

      class="pastemessage">You can also paste this traceback into

      a <a href="https://gist.github.com/">gist</a>:

      <input type="submit" value="create paste"></span>

    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):

  File &quot;/home/tissuemaps/.local/lib/python2.7/site-packages/werkzeug/wsgi.py&quot;, line 703, in __next__

  File &quot;/home/tissuemaps/.local/lib/python2.7/site-packages/werkzeug/wrappers.py&quot;, line 81, in _iter_encoded

    for item in iterable:

  File &quot;/home/tissuemaps/tmserver/tmserver/api/feature.py&quot;, line 314, in generate_feature_matrix

    site_id, layer_lut.keys()

  File &quot;/home/tissuemaps/tmserver/tmserver/api/mapobject.py&quot;, line 132, in _get_mapobjects_at_site

    order_by(tm.Mapobject.id).\

  File &quot;/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py&quot;, line 2679, in all

  File &quot;/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py&quot;, line 2831, in __iter__

    return self._execute_and_instances(context)

  File &quot;/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py&quot;, line 2854, in _execute_and_instances

    result = conn.execute(querycontext.statement, self._params)

  File &quot;/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py&quot;, line 945, in execute

    return meth(self, multiparams, params)

  File &quot;/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py&quot;, line 263, in _execute_on_connection

    return connection._execute_clauseelement(self, multiparams, params)

  File &quot;/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1053, in _execute_clauseelement

    compiled_sql, distilled_params

  File &quot;/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1189, in _execute_context

  File &quot;/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1393, in _handle_dbapi_exception

  File &quot;/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/util/compat.py&quot;, line 203, in raise_from_cause

    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File &quot;/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1182, in _execute_context

  File &quot;/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/default.py&quot;, line 470, in do_execute

    cursor.execute(statement, parameters)

InternalError: (psycopg2.InternalError) failed to execute job 26183

DETAIL:  Failure due to failed task 96

 [SQL: 'SELECT mapobjects.id AS mapobjects_id, mapobject_segmentations.label AS mapobject_segmentations_label, mapobject_segmentations.segmentation_layer_id AS mapobject_segmentations_segmentation_layer_id \nFROM mapobjects JOIN mapobject_segmentations ON mapobjects.id = mapobject_segmentations.mapobject_id \nWHERE mapobjects.mapobject_type_id = %(mapobject_type_id_1)s AND ST_Intersects(mapobject_segmentations.geom_centroid, ST_GeomFromEWKB(%(ST_GeomFromEWKB_1)s)) AND mapobject_segmentations.segmentation_layer_id IN (%(segmentation_layer_id_1)s, %(segmentation_layer_id_2)s, %(segmentation_layer_id_3)s, %(segmentation_layer_id_4)s, %(segmentation_layer_id_5)s) ORDER BY mapobjects.id'] [parameters: {'ST_GeomFromEWKB_1': &lt;read-only buffer for 0x7f263f2cdf30, size 93, offset 0 at 0x7f263a137730&gt;, 'segmentation_layer_id_3': 11, 'segmentation_layer_id_2': 10, 'mapobject_type_id_1': 10, 'segmentation_layer_id_1': 8, 'segmentation_layer_id_4': 6, 'segmentation_layer_id_5': 7}]</textarea>

<div class="explanation">

  The debugger caught an exception in your WSGI application.  You can now

  look at the traceback which led to the error.  <span class="nojavascript">

  If you enable JavaScript you can also use additional features such as code

  execution (if the evalex feature is enabled), automatic pasting of the

  exceptions and much more.</span>

      <div class="footer">

        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your

        friendly Werkzeug powered traceback interpreter.

    <div class="pin-prompt">

      <div class="inner">

          The console is locked and needs to be unlocked by entering the PIN.

          You can find the PIN printed out on the standard output of your

          shell that runs the server.

            <input type=text name=pin size=14>

            <input type=submit name=btn value="Confirm Pin">

Traceback (most recent call last):

  File "/home/tissuemaps/.local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 703, in __next__

  File "/home/tissuemaps/.local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 81, in _iter_encoded

    for item in iterable:

  File "/home/tissuemaps/tmserver/tmserver/api/feature.py", line 314, in generate_feature_matrix

    site_id, layer_lut.keys()

  File "/home/tissuemaps/tmserver/tmserver/api/mapobject.py", line 132, in _get_mapobjects_at_site

    order_by(tm.Mapobject.id).\

  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2679, in all

  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2831, in __iter__

    return self._execute_and_instances(context)

  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2854, in _execute_and_instances

    result = conn.execute(querycontext.statement, self._params)

  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute

    return meth(self, multiparams, params)

  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection

    return connection._execute_clauseelement(self, multiparams, params)

  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement

    compiled_sql, distilled_params

  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context

  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception

  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause

    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context

  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute

    cursor.execute(statement, parameters)

InternalError: (psycopg2.InternalError) failed to execute job 26183

DETAIL:  Failure due to failed task 96

 [SQL: 'SELECT mapobjects.id AS mapobjects_id, mapobject_segmentations.label AS mapobject_segmentations_label, mapobject_segmentations.segmentation_layer_id AS mapobject_segmentations_segmentation_layer_id \nFROM mapobjects JOIN mapobject_segmentations ON mapobjects.id = mapobject_segmentations.mapobject_id \nWHERE mapobjects.mapobject_type_id = %(mapobject_type_id_1)s AND ST_Intersects(mapobject_segmentations.geom_centroid, ST_GeomFromEWKB(%(ST_GeomFromEWKB_1)s)) AND mapobject_segmentations.segmentation_layer_id IN (%(segmentation_layer_id_1)s, %(segmentation_layer_id_2)s, %(segmentation_layer_id_3)s, %(segmentation_layer_id_4)s, %(segmentation_layer_id_5)s) ORDER BY mapobjects.id'] [parameters: {'ST_GeomFromEWKB_1': <read-only buffer for 0x7f263f2cdf30, size 93, offset 0 at 0x7f263a137730>, 'segmentation_layer_id_3': 11, 'segmentation_layer_id_2': 10, 'mapobject_type_id_1': 10, 'segmentation_layer_id_1': 8, 'segmentation_layer_id_4': 6, 'segmentation_layer_id_5': 7}]

```

**Comment by hackermd** [comment]
Probably related to citusdata/citus#1325

**Comment by jluethi** [comment]
If this is related to a worker overload, as suggested in https://github.com/citusdata/citus/issues/1325, how could we decrease that load? Are the download calls made one after the other or all in parallel?

**Comment by HackerMD** [comment]
I just realized that you can of course also directly connect to the application server via `tmclient`:

```
tm_client -H app.tissuemaps.org -P 8080 -u markus experiment ls
```

This should circumvent all problems related to communication between NGINX and uWSGI of the socket.
