### ISSUE TITLE
Database connection issue while downloading and processing simultaneously

### ISSUE THREAD

**Issue by scottberry** [pelkmanslab/TissueMAPS-OLD#72]
We have noticed an intermittent issue with database connections that has been occurring on chimp and I now have on my own instance. I may have some more clue to the source of this error now because it occurred while I was running one jterator pipeline and simultaneously downloading data from another experiment. Both failed at around the same time (16:03 to 16:10 7/5/2017).

Here is the error log two of the jterator run jobs:

```
2017-05-07 16:03:46 | ERROR    | sqlalchemy.pool.QueuePool                | Exception during reset or similar
Traceback (most recent call last):
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
    fairy._reset(pool)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 829, in _reset
    pool._dialect.do_rollback(self)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 440, in do_rollback
    dbapi_connection.rollback()
InterfaceError: connection already closed

JOB FAILED:
'NoneType' object has no attribute 'get_backend_pid'
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/cli.py", line 284, in __main__
    cli_instance(arguments)
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/cli.py", line 343, in __call__
    method(**method_args)
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/jterator/cli.py", line 78, in run
    api.run_job(batch)
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/jterator/api.py", line 610, in run_job
    self._save_pipeline_outputs(store)
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/jterator/api.py", line 502, in _save_pipeline_outputs
    conn, values, mapobject_ids[label], t
  File "/home/tissuemaps/tmlibrary/tmlib/models/utils.py", line 692, in __exit__
    self._connection.close()
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 960, in close
    self._checkin()
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 811, in _checkin
    self._pool, None, self._echo, fairy=self)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 703, in _finalize_fairy
    connection_record.checkin()
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 545, in checkin
    pool.dispatch.checkin(connection, self)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 218, in __call__
    fn(*args, **kw)
  File "/home/tissuemaps/tmlibrary/tmlib/models/utils.py", line 209, in _on_pool_checkin
    dbapi_con.get_backend_pid()
```

```
JOB FAILED:
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

  File "/home/tissuemaps/tmlibrary/tmlib/workflow/cli.py", line 284, in __main__
    cli_instance(arguments)
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/cli.py", line 343, in __call__
    method(**method_args)
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/jterator/cli.py", line 78, in run
    api.run_job(batch)
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/jterator/api.py", line 610, in run_job
    self._save_pipeline_outputs(store)
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/jterator/api.py", line 369, in _save_pipeline_outputs
    with tm.utils.ExperimentSession(self.experiment_id) as session:
  File "/home/tissuemaps/tmlibrary/tmlib/models/utils.py", line 634, in __enter__
    exists = _create_schema_if_not_exists(connection, self._schema)
  File "/home/tissuemaps/tmlibrary/tmlib/models/utils.py", line 153, in _create_schema_if_not_exists
    'schema': schema_name
2017-05-07 16:10:43 | ERROR    | sqlalchemy.pool.QueuePool                | Exception during reset or similar
Traceback (most recent call last):
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
    fairy._reset(pool)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 829, in _reset
    pool._dialect.do_rollback(self)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 440, in do_rollback
    dbapi_connection.rollback()
InterfaceError: connection already closed
Exception AttributeError: "'NoneType' object has no attribute 'get_backend_pid'" in <function <lambda> at 0x7f6f20186848> ignored
```

And the error log from the download:
```
2017-05-07 16:05:14 | INFO     | tmclient.api                             | download metadata for experiment "20170411_Kim2-Sba_ScalingFISH_repeat" and object type "Cells"
2017-05-07 16:05:14 | DEBUG    | tmclient.api                             | get mapobject type ID for experiment "20170411_Kim2-Sba_ScalingFISH_repeat" and mapobjec type "Cells"
2017-05-07 16:05:14 | DEBUG    | tmclient.base                            | url: http://wombat:80/api/experiments/dG1hcHMxMQ==/mapobject_types?name=Cells
2017-05-07 16:10:15 | ERROR    | tmclient.api                             | 500 Server Error: INTERNAL SERVER ERROR for url: http://wombat:80/api/experiments/dG1hcHMxMQ==/mapobject_types?name=Cells
```

@HackerMD @riccardomurri @jluethi @reinouddegroot

**Comment by riccardomurri** [comment]
Looks like the same issue as #67

**Comment by jluethi** [comment]
Yes, this may have been the trigger for Issue 67, as this issue also occured when Scott ran Jterator pipelines and Reinoud ran a data upload

**Comment by scottberry** [comment]
Indeed this is the same issue
